
* Prolegomena: Why this Document?
  
  I recently began studying Dutch.  As a kid, I had briefly tried to
  teach myself from Gerdi Quist and Lesley Gilbert's aptly-named
  _Teach Yourself Dutch_, but learned little and forgot what little I
  learned.  More recently, I picked up Jan Fenoulhet's _Dutch in Three
  Months_, which felt more like "Dutch in the Limit of Infinite Time".
  Despite the advantages I had (personal access to a generous and
  patient native speaker, the relative linguistic proximity of
  English), Dutch wasn't sticking.  

  A very severe natural deadline was approaching: I had planned a trip
  to Belgium, where roughly three-fifths of the population speaks a
  dialect of Dutch called Flemish.  Though learning another language
  in adulthood is a life-long process, I had only a few months to
  bootstrap myself in Dutch, and my free time in that period would be
  heavily constrained by other commitments.  I began to think
  seriously about how to make optimal use of what time I had left.

  With all due respect to the authors of the books named above, who
  are professionals in language instruction, I felt my frustration
  with the texts growing.  Within the first few chapters in
  Frenoulhet's book, for example, the reader is confronted with the
  following piece of vocabulary:

: de pruik - wig
  
  which may be the least useful word I have ever learned in any
  language.  (To pick only a few examples, "pruik" comes before "heel"
  (very), "mijn" (my), and "uit" (out of) in the book).  Perhaps the
  choice of "pruik" was not /totally/ unmotivated (the word contains
  the "ui" diphthong, which many English speakers find challenging),
  but it is difficult to imagine a word less suited to be one of the
  first fifty a new student learns.

  After a few more weeks of this,during which I learned helpful bits
  like "shop window" (de etalage), "worn out" (versleten) and "it's
  not a pretty sight!" (het is geen gezicht!), I joked to my Belgian
  friend that I wished I could just write the book on Dutch that I'd
  rather be reading, then read /that/.  

  Though obviously tongue-in-cheek, I thought this approach would
  offer me two significant advantages.  Firstly, I would be free to
  structure my study to suit my own cognitive idiosyncrasies.  For
  example, I prefer to emphasize grammar initially and fill in the
  vocabulary later, which seems to be the opposite of the dominant
  approach in language instruction.  I could also prioritize my own
  goals for learning the language: I would like to be able to read a
  real Dutch-language newspaper as quickly as possible, whereas other
  competencies like accent are not as important to me as long as I can
  make myself understood.  This approach is not for everybody: it
  requires a native speaker who will be tolerant of questions.
  Moreover, if your native speaker does not possess formal training in
  linguistics, their explanations for why certain features of the
  language fall out as they do may be unilluminating or even wrong:
  their judgments should just be taken as data, or oracular
  pronouncements.

  This set of notes is my attempt to do just that.


  
