
* Prolegomena: Why this Document?
  
  I recently began studying Dutch.  As a kid, I had briefly tried to
  teach myself from Gerdi Quist and Lesley Gilbert's aptly-named
  _Teach Yourself Dutch_, but learned little and forgot what little I
  learned.  More recently, I picked up Jan Fenoulhet's _Dutch in Three
  Months_, which felt more like "Dutch in the Limit of Infinite Time".
  Despite the advantages I had (personal access to a generous and
  patient native speaker, the relative linguistic proximity of
  English), Dutch wasn't sticking.  

  A very severe natural deadline was approaching: I had planned a trip
  to Belgium, where roughly three-fifths of the population speaks a
  dialect of Dutch called Flemish.  Though learning another language
  in adulthood is a life-long process, I had only a few months to
  bootstrap myself in Dutch, and my free time in that period would be
  heavily constrained by other commitments.  I began to think
  seriously about how to make optimal use of what time I had left.

  With all due respect to the authors of the books named above, who
  are professionals in language instruction, I felt my frustration
  with the texts growing.  Within the first few chapters in
  Frenoulhet's book, for example, the reader is confronted with the
  following piece of vocabulary:

: de pruik - wig
  
  which may be the least useful word I have ever learned in any
  language.  (To pick only a few examples, "pruik" comes before "heel"
  (very), "mijn" (my), and "uit" (out of) in Frenoulhet).  Perhaps the
  choice of "pruik" was not /totally/ unmotivated (the word contains
  the "ui" diphthong, which many English speakers find challenging),
  but it is difficult to imagine a word less suited to be one of the
  first fifty a new student learns.

  
